//
//  Hats.cpp
//  Skytool
//
//  Created by Manith Kha on 27/12/21.
//

#include "Hats.h"

using namespace std;

map<uint16_t, string> hatsMap = {
    {14, "Anvil Hat"},
    {44, "Balloon Hat"},
    {15, "Beret"},
    {16, "Birthday Hat"},
    {17, "Bone Head"},
    {18, "Bowler Hat"},
    {21, "Chef Hat"},
    {1, "Combat Hat"},
    {8, "Coonskin Cap"},
    {42, "Cossack Hat"},
    {22, "Cowboy Hat"},
    {28, "Crown of Light"},
    {26, "Eye Hat"},
    {10, "Fancy Hat"},
    {27, "Fez"},
    {43, "Flower Hat"},
    {5, "General's Hat"},
    {45, "Happy Birthday!"},
    {29, "Jester Hat"},
    {25, "Lil Devil"},
    {4, "Miner Hat"},
    {31, "Moose Hat"},
    {2, "Napoleon Hat"},
    {33, "Pan Hat"},
    {41, "Pirate Doo Rag"},
    {6, "Pirate Hat"},
    {32, "Plunger Head"},
    {7, "Propeller Hat"},
    {40, "Pumpkin Hat"},
    {23, "Rocker Hair"},
    {34, "Rocket Hat"},
    {24, "Royal Crown"},
    {35, "Santa Hat"},
    {13, "Spiked Hat"},
    {3, "Spy Gear"},
    {9, "Straw Hat"},
    {36, "Tiki Hat"},
    {11, "Top Hat"},
    {37, "Trojan Helmet"},
    {20, "Tropical Turban"},
    {38, "Unicorn Hat"},
    {12, "Viking Helmet"},
    {19, "Wabbit Ears"},
    {30, "Winged Hat"},
    {39, "Wizard Hat"},
    //Giants
    {59, "Archer Hat"},
    {88, "Atom Hat"},
    {67, "Battle Helmet"},
    {87, "Biter Hat"},
    {68, "Bottle Cap Hat"},
    {48, "Bowling Pin Hat"},
    {94, "Bronze Top Hat"},
    {83, "Caesar Hat"},
    {70, "Carrot Hat"},
    {64, "Dancer Hat"},
    {93, "Dangling Carrot Hat"},
    {72, "Elf Hat"},
    {50, "Firefighter Hat"},
    {73, "Fishing Hat"},
    {84, "Flower Fairy Hat"},
    {85, "Funnel Hat"},
    {74, "Future Hat"},
    {96, "Gold Top Hat"},
    {51, "Graduation Hat"},
    {92, "Knight Helm"},
    {91, "Kufi Hat"},
    {52, "Lampshade Hat"},
    {53, "Mariachi Hat"},
    {75, "Nefertiti Hat"},
    {49, "Officer Hat"},
    {77, "Pants Hat"},
    {55, "Paper Fast Food Hat"},
    {56, "Pilgrim Hat"},
    {57, "Police Siren Hat"},
    {78, "Princess Hat"},
    {58, "Purple Fedora"},
    {90, "Rasta Hat"},
    {61, "Safari Hat"},
    {62, "Sailor Hat"},
    {86, "Scrumshanks Hat"},
    {82, "Showtime Hat"},
    {95, "Silver Top Hat"},
    {89, "Sombrero"},
    {79, "Toy Soldier Hat"},
    {65, "Traffic Cone Hat"},
    {80, "Trucker Hat"},
    {66, "Turban"},
    {81, "Umbrella Hat"},
    {46, "Vintage Baseball Cap"},
    //Swap force
    {121, "Asteroid Hat"},
    {120, "Aviator's Cap"},
    {150, "Awesome Hat"},
    {149, "Bacon Bandana"},
    {117, "Beacon Hat"},
    {126, "Beanie Cap"},
    {112, "Bearskin Cap"},
    {101, "Boater Hat"},
    {104, "Boonie Hat"},
    {140, "Cactus Hat"},
    {109, "Capuchon"},
    {151, "Card Shark Hat"},
    {139, "Clockwork Hat"},
    {123, "Creepy Helm"},
    {137, "Crown of Flames"},
    {115, "Crown of Frost"},
    {122, "Crystal Hat"},
    {93, "Dangling Carrot Hat"},
    {125, "Deely Boppers"},
    {144, "Elephant Hat"},
    {148, "Eyefro"},
    {124, "Fancy Ribbon"},
    {113, "Fishbone Hat"},
    {118, "Flower Garland"},
    {116, "Four Winds Hat"},
    {107, "Gaucho Hat"},
    {130, "Glittering Tiara"},
    {142, "Gloop Hat"},
    {131, "Great Helm"},
    {99, "Greeble Hat"},
    {152, "Jolly Hat"},
    {153, "Kickoff Hat"},
    {127, "Leprechaun Hat"},
    {129, "Life Preserver Hat"},
    {136, "Lilypad Hat"},
    {135, "Obsidian Helm"},
    {55, "Paper Fast Food Hat"},
    {111, "Peacock Hat"},
    {143, "Puma Hat"},
    {97, "Rain Hat"},
    {108, "Roundlet"},
    {138, "Runic Headband"},
    {105, "Sawblade Hat"},
    {128, "Shark Hat"},
    {114, "Ski Cap"},
    {141, "Skullhelm"},
    {132, "Space Helmet"},
    {154, "Springtime Hat"},
    {102, "Stone Hat"},
    {103, "Stovepipe Hat"},
    {146, "Teeth Top Hat"},
    {98, "The Outsider"},
    {145, "Tiger Skin Cap"},
    {119, "Tree Branch"},
    {110, "Tricorn Hat"},
    {147, "Turkey Hat"},
    {133, "UFO Hat"},
    {100, "Volcano Hat"},
    {134, "Whirlwind Diadem"},
    {106, "Zombeanie"},
    //Trap team
    {211, "Alarm Clock Hat"},
    {218, "Bat Hat"},
    {212, "Batter Up Hat"},
    {155, "Beetle Hat"},
    {237, "Bellhop Hat"},
    {195, "Bobby"},
    {156, "Brain Hat"},
    {157, "Brainiac Hat"},
    {238, "Bronze Arkeyan Helm"},
    {158, "Bucket Hat"},
    {234, "Candle Hat"},
    {232, "Candy Cane Hat"},
    {246, "Carnival Hat"},
    {160, "Ceiling Fan Hat"},
    {187, "Classic Pot Hat"},
    {163, "Clown Bowler Hat"},
    {162, "Clown Classic Hat"},
    {247, "Coconut Hat"},
    {164, "Colander Hat"},
    {252, "Core Of Light Hat"},
    {166, "Cornucopia Hat"},
    {189, "Crazy Light Bulb Hat"},
    {214, "Croissant Hat"},
    {167, "Cubano Hat"},
    {168, "Cycling Hat"},
    {169, "Daisy Crown"},
    {235, "Dark Helm"},
    {159, "Desert Crown"},
    {170, "Dragon Skull"},
    {233, "Eggshell Hat"},
    {203, "Extreme Viking Hat"},
    {217, "Eye of Kaos Hat"},
    {220, "Firefly Jar"},
    {198, "Flight Attendant Hat"},
    {174, "Garrison Hat"},
    {173, "Generalissimo"},
    {226, "Gold Arkeyan Helm"},
    {175, "Gondolier Hat"},
    {196, "Hedgehog Hat"},
    {213, "Horns Be With You Hat"},
    {176, "Hunting Hat"},
    {161, "Imperial Hat"},
    {177, "Juicer Hat"},
    {165, "Kepi Hat"},
    {178, "Kokoshnik"},
    {219, "Light Bulb Hat"},
    {222, "Lighthouse Beacon Hat"},
    {172, "Lil' Elf Hat"},
    {179, "Medic Hat"},
    {180, "Melon Hat"},
    {192, "Metal Fin Hat"},
    {229, "Miniature Skylands Hat"},
    {250, "Molekin Mountain Hat"},
    {199, "Monday Hat"},
    {181, "Mountie Hat"},
    {224, "Night Cap"},
    {182, "Nurse Hat"},
    {253, "Octavius Cloptimus Hat"},
    {186, "Old-Time Movie Hat"},
    {171, "Outback Hat"},
    {183, "Palm Hat"},
    {184, "Paperboy Hat"},
    {185, "Parrot Nest"},
    {236, "Planet Hat"},
    {210, "Pork Pie Hat"},
    {228, "Pyramid Hat"},
    {188, "Radar Hat"},
    {216, "Rainbow Hat"},
    {190, "Rubber Glove Hat"},
    {209, "Rude Boy Hat"},
    {191, "Rugby Hat"},
    {204, "Scooter Hat"},
    {221, "Shadow Ghost Hat"},
    {200, "Sherpa Hat"},
    {194, "Shower Cap"},
    {239, "Silver Arkeyan Helm"},
    {243, "Skipper Hat"},
    {193, "Sleuth Hat"},
    {197, "Steampunk Hat"},
    {225, "Storm Hat"},
    {206, "Synchronized Swimming Cap"},
    {223, "Tin Foil Hat"},
    {227, "Toucan Hat"},
    {201, "Trash Lid"},
    {208, "Tribal Hat"},
    {202, "Turtle Hat"},
    {205, "Volcano Island Hat"},
    {215, "Weather Vane Hat"},
    {207, "William Tell Hat"},
    //Superchargers
    {261, "Burn-Cycle Header"},
    {271, "Buzz Wing Hat"},
    {276, "Crypt Crusher Cap"},
    {259, "Dive Bomber Hat"},
    {279, "Eon’s Helm"},
    {268, "Gold Rusher Cog Cap"},
    {274, "Hot Streak Headpiece"},
    {263, "Jet Stream Helmet"},
    {278, "Kaos Krown"},
    {277, "Mags Hat"},
    {262, "Reef Ripper Helmet"},
    {260, "Sea Shadow Hat"},
    {267, "Shark Tank Topper"},
    {272, "Shield Striker Helmet"},
    {275, "Sky Slicer Hat"},
    {264, "Soda Skimmer Shower Cap"},
    {269, "Splatter Splasher Spires"},
    {266, "Stealth Stinger Beanie"},
    {273, "Sun Runner Spikes"},
    {270, "Thump Trucker’s Hat"},
    {265, "Tomb Buggy Skullcap"}
};

std::string getHatName(uint16_t code) {
    if (code == 0) return "None";
    map<uint16_t, string>::iterator it = hatsMap.find(code);
    if (it == hatsMap.end()) {
        return "Unknown";
    } else {
        return it->second;
    }
}

uint8_t getHatGame(uint16_t code) {
    if (code <= 45) {
        return 0;
    } else if (code <= 96) {
        return 1;
    } else if (code <= 155) {
        return 2;
    } else if (code <= 255) {
        return 3;
    } else return 4;
}
uint16_t getHatCode(std::string hatName) {
    for (map<uint16_t, string>::iterator it = hatsMap.begin(); it != hatsMap.end(); it++) {
        if (it->second == hatName) return (it->first);
    }
    return 0xFFFF;
}

        




